### ISSUE TITLE
Any support for rock64 board? 

### ISSUE THREAD

**Issue by jroth** [ludiazv/octocitrico#5]
Currently there are some Rock64 (Pine64) v2 boards on sale for rock bottom prices with power supply and case.  Any chance this will work for that board?

**Comment by ludiazv** [comment]
I think so. This board is not officially supported by armbian but it's possible to build armbian for it as community support.

I don't know if is stable or not as I never tested this board. This is powerful board and will have no limitations to run octoprint,

**Comment by jroth** [comment]
Very cool.   I was running Armbian_20.08.1_Rock64_buster_current_5.8.6.img and starting to install manually.

**Comment by jroth** [comment]
Got it running following the main wiki, and also this guide:     https://daumemo.com/installing-octoprint-on-orangepi-zero-part-1/

Just printed my first print.   Still need to get video working.

**Comment by ludiazv** [comment]
Would you like to contribute to the project building and/or testing an image for this board?

**Comment by jroth** [comment]
Definitely looking into it.   I haven't managed to get the camera working, but I have octoprint, with a few plugins worked out, on top of the plain Armbian image.

**Comment by zmrde** [comment]
Hey guys. Anything new? Looking forward to have this project supported on rock64. Thanks!

**Comment by ludiazv** [comment]
working on the new release. I will include a WIP image for this board.

**Comment by zmrde** [comment]
Is the release scheduled to a date? Thanks

**Comment by ludiazv** [comment]
I'm testing now as they new release will only use python3. If everything goes well I will release the new images in one or two days.

**Comment by ludiazv** [comment]
Hi all,
  I just published a custom image for Rock64. I have no way to test it as I do not have this board. If you can test it please send over feedback.

**Comment by doctorevil30564** [comment]
just purchased a rock64 1GB board and a power supply to experiment with. I primarily run slightly older 3B or 3B+ raspberry Pi boards for all of my current printers, but I'd like to have other cheaper options for future growth. I've downloaded the current custom image for a rock64 and I'll try to get some feedback posted as soon as I have a chance to test it out.

**Comment by doctorevil30564** [comment]
OK the Rock64 image works well except for the issue with /dev/video0 not working for the webcam.

I used these commands added to /etc/rc.local to get it working after a reboot

sudo rm /dev/video0
sudo chmod -R 777 /dev
mv /dev/video1 /dev/video0

it survived running an apt-get update/upgrade command, and It survived updating octoprint to the latest version.

**Comment by jroth** [comment]
My first sd card died.   I reinstalled the Armbian_20.11.4_Rock64_buster_current_5.9.16 release for rock64.  

as-is worked fine with the note above regarding video - upgrade to current linux did not work

**Comment by jroth** [comment]
Grabbed Armbian_22.02.0-trunk_Rock64_bullseye_current_5.15.31 - updated to current supported, applied the fixes to the haproxy config, but I'm still having an issue starting octoprint.  Will need to debug more.  Definitely close to working on current build.

**Comment by jroth** [comment]
Quick rebuild of octoprint, pulling latest, and it's working again.   Thanks!
source ~/oprint/bin/activate
pip install --force-reinstall OctoPrint

**Comment by jroth** [comment]
Rock solid.  No issues to report ~10 prints later.  Couldn’t be happier :)   I looked back and I paid $16 for this board, with power supply!  @ludiazv happy to test upcoming releases if needed.  Going to close this out for now.
